export const teamMembers = [
    {
      id: 1,
      name: "OSWALD FERNANDES",
      position: "Chief Executive Officer",
      image: "/IT-planning.jpg",
      bio: "A results-driven professional with extensive experience in leading local and global cross-functional teams, driving customer success, and delivering innovative technology solutions. Proven ability to connect people, processes, and technologies to achieve business outcomes in complex and dynamic environments. I bring a unique blend of strategic vision and hands-on technical project and program expertise. My goal is to leverage my leadership skills and technical experience of Cross Domain Enterprise and Service Provider technologies to drive growth, profitability and innovation.",
      expertise: [
        "Technical Writing", 
        "Program/Project/Portfolio Management", 
        "Jira", 
        "Confluence", 
        "4xCCIE(Active)", 
        "CMNA", 
        "DEVNET", 
        "Python", 
        "SQL", 
        "Terraform", 
        "Tableau", 
        "RedHat Linux", 
        "Jupyter Notebook", 
        "NETCONF", 
        "REST-API", 
        "Postman", 
        "VIRL", 
        "GNS3", 
        "CML", 
        "IOS", 
        "IOS-XE", 
        "IOS-XR", 
        "NX-OS", 
        "SDWAN", 
        "MPLS", 
        "BGP", 
        "VXLAN", 
        "EVPN", 
        "DSF(Disaggregated Switch Fabric via Scheduled Ethernet)", 
        "RCoE", 
        "OSPF", 
        "ISIS", 
        "EIGRP", 
        "VRF", 
        "ACI", 
        "SAE", 
        "SASE", 
        "Visio", 
        "PowerPoint", 
        "Word", 
        "Excel", 
        "Windows 11", 
        "Windows 2016", 
        "ML", 
        "AI", 
        "ChatGPT(LLM)", 
        "AWS", 
        "GCP", 
        "Cloud", 
        "IAAS", 
        "PAAS", 
        "Ansible", 
        "YANG-Models", 
        "DataScience:Pandas", 
        "ML", 
        "LLM"
      ],      
      education: "BS (Honors: Magna Cum Laude) in Information Technology and Cyber Security.",
    //   linkedin: "https://linkedin.com/in/johnsmith",
      email: "oswfernand@yahoo.com"
    },
    {
      id: 2,
      name: "Sharan Hiremath",
      position: "Coordinator",
      image: "/service3.jpg",
      bio: "Sharan is a technology visionary with deep expertise in cloud architecture, AI solutions, and mobile technologies. With a background in both research and practical implementation, she drives Osvan's technical strategy and ensures our solutions remain at the cutting edge.",
      expertise: ["Cloud Architecture", "AI Implementation", "5G Technologies"],
      education: "Master's in Computer Application KLS Gogte Institute of Technology, Belgaum",
      // linkedin: "https://linkedin.com/in/sarahjohnson"
    }
  ];
